replicaCount: 2
image:
  repository: nginx
  tag: stable
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

ingress:
  enabled: true
  host: homework.otus
  path: /

probes:
  enabled: false

persistence:
  enabled: true
  size: 1Gi
  storageClassName: kuber-sc
