apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mysql-operator-binding
subjects:
  - kind: ServiceAccount
    name: mysql-operator-sa
    namespace: homework
roleRef:
  kind: ClusterRole
  name: mysql-operator-role
  apiGroup: rbac.authorization.k8s.io
