apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mysqls.otus.homework
spec:
  group: otus.homework
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required: ["image", "database", "password", "storage_size"]
              properties:
                image:
                  type: string
                  description: Docker image to deploy
                database:
                  type: string
                  description: Name of the database
                password:
                  type: string
                  description: Password for the database
                storage_size:
                  type: string
                  description: Storage size for the database
      subresources:
        status: {}
  scope: Namespaced
  names:
    plural: mysqls
    singular: mysql
    kind: MySQL
    shortNames:
      - mydb
