apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: homework
data:
  stub_status.conf: |
    server {
        listen 8080;
        location /stub_status {
            stub_status;
            allow 127.0.0.1;
            deny all;
        }
    }
