apiVersion: v1
kind: Service
metadata:
  name: nginx-metrics-svc
  namespace: homework
spec:
  selector:
    app: nginx-metrics
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
