apiVersion: v1
kind: Service
metadata:
  name: nginx-metrics-svc
  namespace: homework
  labels:
    app: nginx-metrics
spec:
  ports:
  - name: metrics
    port: 9113
    targetPort: 9113
  selector:
    app: nginx-metrics
