server:
  http_listen_port: 3101
  grpc_listen_port: 0
  log_level: info

clients:
  - url: http://loki-gateway.loki.svc.cluster.local/loki/api/v1/push
    headers:
      X-Scope-OrgID: default

positions:
  filename: /run/promtail/positions.yaml

scrape_configs:
  - job_name: kubernetes-pods
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: namespace
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: pod
      - source_labels: [__meta_kubernetes_pod_container_name]
        action: replace
        target_label: container
