loki:
  auth_enabled: false

  structuredConfig:
    server:
      http_listen_port: 3100
    common:
      path_prefix: /var/loki
      replication_factor: 1
    storage_config:
      aws:
        s3: s3://${AWS_ACCESS_KEY_ID}:${AWS_SECRET_ACCESS_KEY}@storage.yandexcloud.net/loki-logs-otus
        s3forcepathstyle: true
      tsdb_shipper:
        active_index_directory: /var/loki/index
        cache_location: /var/loki/index_cache
    schema_config:
      configs:
        - from: "2025-06-13"
          store: tsdb
          object_store: s3
          schema: v13
          index:
            prefix: index_
            period: 24h
    compactor:
      working_directory: /var/loki/compactor
    limits_config:
      allow_structured_metadata: false

  extraArgs:
    - -config.expand-env=true

  extraEnvFrom:
    - secretRef:
        name: loki-s3-creds

  backend:
    replicas: 1
  write:
    replicas: 1
  read:
    replicas: 1

  storage:
    type: s3
    bucketNames:
      chunks: loki-logs-otus
      ruler: loki-logs-otus
      admin: loki-logs-otus

  schemaConfig:
    configs:
      - from: "2000-01-01"
        store: boltdb
        object_store: filesystem
        schema: v11
        index:
          prefix: dummy
          period: 168h

  gateway:
    enabled: true
    nginx:
      enabled: true
    nginxConfig:
      auth_enabled: false

ruler:
  enabled: false
